openapi: 3.0.0
info:
  title: SRE Platform API
  version: 1.0.0
  description: |
    Comprehensive SRE Platform API for incident management, resource monitoring, automation, and system observability.

    ## Features
    - 📊 Dashboard Management
    - 🚨 Incident & Alert Management
    - 🔧 Resource & Topology Management
    - 🤖 Automation & Playbooks
    - 📈 Analysis & Insights
    - 👥 IAM & Access Control
    - 📢 Notification Management
    - ⚙️ System Settings

  contact:
    name: SRE Platform Team
    email: sre@example.com
  license:
    name: MIT

servers:
  - url: /api/v1
    description: SRE Platform API Server

security:
  - bearerAuth: []

tags:
  - name: Dashboards
    description: 儀表板管理 (Dashboard management and visualization)
  - name: Incidents
    description: 事件管理 (Incident tracking and lifecycle actions)
  - name: Alert Rules
    description: 告警規則 (Alert rule configuration and automation)
  - name: Silence Rules
    description: 靜音規則 (Silence rule management)
  - name: Resources
    description: 資源管理 (Resource inventory, metrics, and topology)
  - name: Automation
    description: 自動化 (Automation playbooks, executions, and triggers)
  - name: IAM
    description: 身份與存取 (Identity and access management for users, teams, and roles)
  - name: Notifications
    description: 通知管理 (Notification channels, strategies, and delivery history)
  - name: Analysis
    description: 分析中心 (AI-powered analysis and predictive insights)
  - name: Settings
    description: 平台設定 (Platform-wide settings and configurations)
  - name: Logs
    description: 日誌查詢 (Log querying endpoints)
