openapi: 3.0.0
info:
  title: SRE Platform API
  version: 1.0.0
  description: |
    Comprehensive SRE Platform API for incident management, resource monitoring, automation, and system observability.

    ## Features
    - 📊 Dashboard Management
    - 🚨 Incident & Alert Management
    - 🔧 Resource & Topology Management
    - 🤖 Automation & Playbooks
    - 📈 Analysis & Insights
    - 👥 IAM & Access Control
    - 📢 Notification Management
    - ⚙️ System Settings

  contact:
    name: SRE Platform Team
    email: sre@example.com
  license:
    name: MIT

servers:
  - url: http://localhost:4000/api/v1
    description: Development server
  - url: https://api.sre-platform.example.com/api/v1
    description: Production server

security:
  - bearerAuth: []

tags:
  - name: Dashboards
    description: Dashboard management and visualization
  - name: Incidents
    description: Incident tracking and lifecycle actions
  - name: Alert Rules
    description: Alert rule configuration and automation
  - name: Resources
    description: Resource inventory, metrics, and topology
  - name: Automation
    description: Automation playbooks, executions, and triggers
  - name: IAM
    description: Identity and access management for users and teams
  - name: Notifications
    description: Notification channels, strategies, and delivery history
  - name: Analysis
    description: AI-powered analysis and predictive insights
  - name: Users
    description: User directory and access profiles
  - name: Teams
    description: Team structures and membership management
  - name: Roles
    description: Role definitions and permission policies
  - name: Health
    description: Platform health and readiness monitoring
  - name: Metrics
    description: Observability metrics and reporting endpoints
