# Automation Schemas
components:
  schemas:
    # ===================
    # Automation Playbook
    # ===================
    AutomationPlaybook:
      type: object
      required: [id, name, type, content, enabled, created_at]
      properties:
        id:
          type: string
          example: script-restart-service
        name:
          type: string
          example: 重啟服務腳本
        type:
          type: string
          enum: ['Shell Script', 'Python', 'Ansible', 'Terraform']
          example: Shell Script
        content:
          type: string
          example: |
            #!/bin/bash
            systemctl restart nginx
        description:
          type: string
          example: 自動重啟 Nginx 服務
        enabled:
          type: boolean
          example: true
        timeout_seconds:
          type: integer
          default: 300
          example: 120
        parameters:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              type:
                type: string
              required:
                type: boolean
              default:
                type: string
          example:
            - name: service_name
              type: string
              required: true
              default: nginx
        execution_count:
          type: integer
          example: 42
        last_run_at:
          type: string
          format: date-time
          example: "2024-01-15T09:30:00Z"
        last_run_status:
          type: string
          enum: [success, failed, pending]
          example: success
        run_count:
          type: integer
          example: 42
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
          nullable: true

    AutomationPlaybookCreate:
      type: object
      required: [name, type, content]
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 200
        type:
          type: string
          enum: ['Shell Script', 'Python', 'Ansible', 'Terraform']
        content:
          type: string
          minLength: 1
        description:
          type: string
        enabled:
          type: boolean
          default: true
        timeout_seconds:
          type: integer
          default: 300
        parameters:
          type: array
          items:
            type: object

    AutomationPlaybookUpdate:
      type: object
      properties:
        name:
          type: string
        content:
          type: string
        description:
          type: string
        enabled:
          type: boolean
        timeout_seconds:
          type: integer
        execution_count:
          type: integer
        parameters:
          type: array
          items:
            type: object

    # ===================
    # Automation Execution
    # ===================
    AutomationExecution:
      type: object
      required: [id, playbook_id, playbook_name, trigger_type, triggered_by, status, started_at]
      properties:
        id:
          type: string
          example: exec-001
        playbook_id:
          type: string
          example: play-001
        playbook_name:
          type: string
          example: 重啟服務腳本
        incident_id:
          type: string
          nullable: true
          example: INC-001
        alert_rule_id:
          type: string
          nullable: true
          example: rule-cpu-high
        target_resource_id:
          type: string
          nullable: true
          example: res-web-001
        trigger_type:
          type: string
          enum: [Manual, Scheduled, Webhook, Incident, Alert]
          example: Incident
        triggered_by:
          type: string
          example: usr-001
        status:
          type: string
          enum: [Pending, Running, Success, Failed, Cancelled]
          example: Success
        started_at:
          type: string
          format: date-time
          example: "2024-01-15T10:00:00Z"
        completed_at:
          type: string
          format: date-time
          nullable: true
          example: "2024-01-15T10:02:30Z"
        duration_ms:
          type: integer
          example: 150000
        parameters:
          type: object
          additionalProperties:
            type: string
          example:
            namespace: production
        output:
          type: object
          properties:
            stdout:
              type: string
            stderr:
              type: string
          example:
            stdout: Service nginx restarted successfully
            stderr: ''
        logs:
          type: object
          readOnly: true
          properties:
            stdout:
              type: string
            stderr:
              type: string
        error_message:
          type: string
          nullable: true
          example: null
        resolved_incident:
          type: boolean
          example: true

    AutomationExecutionCreate:
      type: object
      required: [playbook_id, trigger_type]
      properties:
        playbook_id:
          type: string
        trigger_type:
          type: string
          enum: [Manual, Scheduled, Webhook, Incident, Alert]
        triggered_by:
          type: string
          description: Identifier of the user initiating the execution
        parameters:
          type: object
          additionalProperties:
            type: string
        incident_id:
          type: string
        alert_rule_id:
          type: string
        target_resource_id:
          type: string

    # ===================
    # Automation Trigger
    # ===================
    AutomationTrigger:
      type: object
      required: [id, name, type, enabled, target_playbook_id, created_at]
      properties:
        id:
          type: string
          example: trigger-daily-backup
        name:
          type: string
          example: 每日備份觸發器
        type:
          type: string
          enum: [Schedule, Webhook, Event]
          example: Schedule
        enabled:
          type: boolean
          example: true
        target_playbook_id:
          type: string
          example: script-backup
        config:
          type: object
          description: Configuration details specific to the trigger type
          properties:
            schedule:
              type: object
              properties:
                cron:
                  type: string
                timezone:
                  type: string
                cron_description:
                  type: string
            webhook:
              type: object
              properties:
                url:
                  type: string
                  format: uri
                secret:
                  type: string
            event:
              type: object
              properties:
                source:
                  type: string
                severity:
                  type: string
        cron:
          type: string
          example: "0 2 * * *"
          description: Cron expression for schedule triggers
        cron_description:
          type: string
          example: "每天凌晨 2 點執行"
        webhook_url:
          type: string
          format: uri
          example: "https://api.example.com/webhook/trigger/backup"
        event_conditions:
          type: object
          example:
            event_type: incident.critical
            severity: critical
        last_triggered_at:
          type: string
          format: date-time
          example: "2024-01-15T02:00:00Z"
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
          nullable: true

    AutomationTriggerCreate:
      type: object
      required: [name, type, enabled, target_playbook_id]
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 200
        type:
          type: string
          enum: [Schedule, Webhook, Event]
        enabled:
          type: boolean
        target_playbook_id:
          type: string
        config:
          type: object
        cron:
          type: string
          description: Required for Schedule type
        event_conditions:
          type: object
          description: Required for Event type

    AutomationTriggerUpdate:
      type: object
      properties:
        name:
          type: string
        enabled:
          type: boolean
        config:
          type: object
        cron:
          type: string
        event_conditions:
          type: object
