# Automation Schemas
components:
  schemas:
    # ===================
    # Automation Playbook
    # ===================
    AutomationPlaybook:
      type: object
      required:
        - id
        - name
        - trigger
        - type
        - content
        - last_run_at
        - last_run_status
        - run_count
        - created_at
        - updated_at
      properties:
        id:
          type: string
          readOnly: true
          example: play-001
        name:
          type: string
          example: 重啟故障 Pod
        trigger:
          type: string
          description: Identifier of the trigger associated with the playbook.
          example: incident.created
        type:
          type: string
          enum: [shell, python, ansible, terraform]
          example: shell
        description:
          type: string
          example: 自動重啟 CrashLoopBackOff 狀態的 Pod。
        content:
          type: string
          example: |
            #!/bin/bash
            kubectl rollout restart deployment "$DEPLOYMENT"
        last_run_at:
          type: string
          format: date-time
          readOnly: true
          example: "2025-09-23T14:05:10Z"
        last_run_status:
          type: string
          enum: [pending, running, success, failed, cancelled]
          readOnly: true
          example: success
        run_count:
          type: integer
          readOnly: true
          example: 12
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/ParameterDefinition'
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        deleted_at:
          type: string
          format: date-time
          readOnly: true
          nullable: true

    ParameterDefinition:
      type: object
      required: [name, label, type, required]
      properties:
        name:
          type: string
          description: The parameter name used in the script.
          example: namespace
        label:
          type: string
          description: The human-readable label for the UI.
          example: 命名空間
        type:
          type: string
          enum: [string, number, enum, boolean]
          example: string
        required:
          type: boolean
        default_value:
          oneOf:
            - type: string
            - type: number
            - type: boolean
          example: production
        options:
          type: array
          description: "A list of options, required if type is 'enum'."
          items:
            type: object
            properties:
              value:
                type: string
              label:
                type: string
        placeholder:
          type: string
          example: "Enter the target namespace"

    AutomationPlaybookCreate:
      type: object
      required: [name, type, content]
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 200
        type:
          type: string
          enum: [shell, python, ansible, terraform]
        content:
          type: string
          minLength: 1
        description:
          type: string
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/ParameterDefinition'

    AutomationPlaybookUpdate:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
          enum: [shell, python, ansible, terraform]
        content:
          type: string
        description:
          type: string
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/ParameterDefinition'

    # ===================
    # Automation Execution
    # ===================
    AutomationExecution:
      type: object
      description: Represents a single run of an automation playbook.
      readOnly: true
      required:
        - id
        - playbook_id
        - playbook_name
        - status
        - trigger_source
        - triggered_by
        - start_time
        - logs
      properties:
        id:
          type: string
          example: exec-001
        playbook_id:
          type: string
          example: play-001
        playbook_name:
          type: string
          example: 重啟故障 Pod
        status:
          type: string
          enum: [pending, running, success, failed, cancelled]
          example: running
        trigger_source:
          type: string
          enum: [manual, schedule, webhook, event, custom, grafana]
          example: manual
        triggered_by:
          type: string
          example: Admin User
        start_time:
          type: string
          format: date-time
          example: "2025-09-23T14:05:10Z"
        end_time:
          type: string
          format: date-time
          nullable: true
          example: "2025-09-23T14:05:15Z"
        duration_ms:
          type: integer
          example: 5000
        parameters:
          type: object
          additionalProperties:
            type: string
          example:
            namespace: production
        logs:
          type: object
          properties:
            stdout:
              type: string
            stderr:
              type: string
          example:
            stdout: Execution started...
            stderr: ""
        incident_id:
          type: string
          nullable: true
          example: INC-002
        alert_rule_id:
          type: string
          nullable: true
          example: rule-002
        target_resource_id:
          type: string
          nullable: true
          example: res-002
        deleted_at:
          type: string
          format: date-time
          nullable: true

    AutomationExecutionRequest:
      type: object
      properties:
        parameters:
          type: object
          additionalProperties:
            type: any
          example:
            namespace: production
            force_restart: true
      description: 執行腳本時可傳入的參數

    # ===================
    # Automation Trigger
    # ===================
    AutomationTrigger:
      type: object
      required:
        - id
        - name
        - type
        - enabled
        - target_playbook_id
        - config
        - creator
        - created_at
        - updated_at
      properties:
        id:
          type: string
          readOnly: true
          example: trigger-daily-backup
        name:
          type: string
          example: 每日備份觸發器
        description:
          type: string
        type:
          type: string
          enum: [schedule, webhook, event]
          example: schedule
        enabled:
          type: boolean
          example: true
        target_playbook_id:
          type: string
          example: script-backup
        retry_policy:
          type: string
          enum: [none, fixed, exponential]
          default: none
        config:
          type: object
          description: Configuration details specific to the trigger type.
          properties:
            cron:
              type: string
              description: "Cron expression (for schedule type)."
              example: "0 2 * * *"
            cron_description:
              type: string
              description: "Human-readable cron description (for schedule type)."
              example: "每天凌晨 2 點執行"
            webhook_url:
              type: string
              format: uri
              description: "The webhook URL to call (for webhook type)."
              example: "https://api.example.com/webhook/trigger/backup"
            event_conditions:
              type: string
              description: "Conditions for the event to trigger the playbook (for event type)."
              example: "severity == 'critical' && resource.type == 'database'"
        last_triggered_at:
          type: string
          format: date-time
          readOnly: true
          example: "2024-01-15T02:00:00Z"
        creator:
          type: string
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        deleted_at:
          type: string
          format: date-time
          readOnly: true
          nullable: true

    AutomationTriggerCreate:
      type: object
      required: [name, type, enabled, target_playbook_id, config]
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
        type:
          type: string
          enum: [schedule, webhook, event]
        enabled:
          type: boolean
          default: true
        target_playbook_id:
          type: string
        retry_policy:
          type: string
          enum: [none, fixed, exponential]
          default: none
        config:
          type: object
          description: "Required configuration based on trigger type."

    AutomationTriggerUpdate:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        enabled:
          type: boolean
        target_playbook_id:
          type: string
        retry_policy:
          type: string
          enum: [none, fixed, exponential]
        config:
          type: object
          description: "Configuration based on trigger type."
