# Automation Schemas
components:
  schemas:
    # ===================
    # Automation Playbook
    # ===================
    AutomationPlaybook:
      type: object
      required: [id, name, type, content, created_at]
      properties:
        id:
          type: string
          example: play-001
        name:
          type: string
          example: 重啟故障 Pod
        type:
          type: string
          enum: [shell, python, ansible, terraform]
          example: shell
        description:
          type: string
          example: 自動重啟 CrashLoopBackOff 狀態的 Pod。
        content:
          type: string
          example: |
            #!/bin/bash
            kubectl rollout restart deployment "$DEPLOYMENT"
        enabled:
          type: boolean
          example: true
        trigger:
          type: string
          example: K8s 告警
        last_run_at:
          type: string
          format: date-time
          example: "2025-09-23T14:05:10Z"
        last_run_status:
          type: string
          enum: [pending, running, success, failed, cancelled]
          example: success
        run_count:
          type: integer
          example: 12
        parameters:
          type: array
          items:
            type: object
            required: [name, label, type]
            properties:
              name:
                type: string
                example: namespace
              label:
                type: string
                example: 命名空間
              type:
                type: string
                example: string
              required:
                type: boolean
                example: true
              default_value:
                type: string
                example: production
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
          nullable: true

    AutomationPlaybookCreate:
      type: object
      required: [name, type, content]
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 200
        type:
          type: string
          enum: [shell, python, ansible, terraform]
        content:
          type: string
          minLength: 1
        description:
          type: string
        enabled:
          type: boolean
          default: true
        trigger:
          type: string
        parameters:
          type: array
          items:
            type: object
            required: [name, label, type]
            properties:
              name:
                type: string
              label:
                type: string
              type:
                type: string
              required:
                type: boolean
              default_value:
                type: string

    AutomationPlaybookUpdate:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
          enum: [shell, python, ansible, terraform]
        content:
          type: string
        description:
          type: string
        enabled:
          type: boolean
        trigger:
          type: string
        parameters:
          type: array
          items:
            type: object
            required: [name]
            properties:
              name:
                type: string
              label:
                type: string
              type:
                type: string
              required:
                type: boolean
              default_value:
                type: string

    # ===================
    # Automation Execution
    # ===================
    AutomationExecution:
      type: object
      required:
        [
          id,
          script_id,
          script_name,
          status,
          trigger_source,
          triggered_by,
          start_time,
        ]
      properties:
        id:
          type: string
          example: exec-001
        script_id:
          type: string
          example: play-001
        script_name:
          type: string
          example: 重啟故障 Pod
        status:
          type: string
          enum: [pending, running, success, failed, cancelled]
          example: running
        trigger_source:
          type: string
          enum: [manual, schedule, webhook, event, custom, grafana]
          example: manual
        triggered_by:
          type: string
          example: Admin User
        start_time:
          type: string
          format: date-time
          example: "2025-09-23T14:05:10Z"
        end_time:
          type: string
          format: date-time
          nullable: true
          example: "2025-09-23T14:05:15Z"
        duration_ms:
          type: integer
          example: 5000
        parameters:
          type: object
          additionalProperties:
            type: string
          example:
            namespace: production
        logs:
          type: object
          properties:
            stdout:
              type: string
            stderr:
              type: string
          example:
            stdout: Execution started...
            stderr: ""
        incident_id:
          type: string
          nullable: true
          example: INC-002
        alert_rule_id:
          type: string
          nullable: true
          example: rule-002
        target_resource_id:
          type: string
          nullable: true
          example: res-002
        error_message:
          type: string
          nullable: true

    AutomationExecutionRequest:
      type: object
      properties:
        parameters:
          type: object
          additionalProperties:
            type: string
          example:
            namespace: production
      description: 執行腳本時可傳入的參數

    # ===================
    # Automation Trigger
    # ===================
    AutomationTrigger:
      type: object
      required: [id, name, type, enabled, target_playbook_id, created_at]
      properties:
        id:
          type: string
          example: trigger-daily-backup
        name:
          type: string
          example: 每日備份觸發器
        type:
          type: string
          enum: [schedule, webhook, event]
          example: schedule
        enabled:
          type: boolean
          example: true
        target_playbook_id:
          type: string
          example: script-backup
        config:
          type: object
          description: Configuration details specific to the trigger type
          properties:
            schedule:
              type: object
              properties:
                cron:
                  type: string
                timezone:
                  type: string
                cron_description:
                  type: string
            webhook:
              type: object
              properties:
                url:
                  type: string
                  format: uri
                secret:
                  type: string
            event:
              type: object
              properties:
                source:
                  type: string
                severity:
                  type: string
        cron:
          type: string
          example: "0 2 * * *"
          description: Cron expression for schedule triggers
        cron_description:
          type: string
          example: "每天凌晨 2 點執行"
        webhook_url:
          type: string
          format: uri
          example: "https://api.example.com/webhook/trigger/backup"
        event_conditions:
          type: object
          example:
            event_type: incident.critical
            severity: critical
        last_triggered_at:
          type: string
          format: date-time
          example: "2024-01-15T02:00:00Z"
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
          nullable: true

    AutomationTriggerCreate:
      type: object
      required: [name, type, enabled, target_playbook_id]
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 200
        type:
          type: string
          enum: [schedule, webhook, event]
        enabled:
          type: boolean
        target_playbook_id:
          type: string
        config:
          type: object
        cron:
          type: string
          description: Required for Schedule type
        event_conditions:
          type: object
          description: Required for Event type

    AutomationTriggerUpdate:
      type: object
      properties:
        name:
          type: string
        enabled:
          type: boolean
        config:
          type: object
        cron:
          type: string
        event_conditions:
          type: object
