import { AutomationExecution } from "../types";

export const PAGE_CONTENT = {
  // Global & Common Strings
  GLOBAL: {
    SEARCH_PLACEHOLDER: '搜尋...',
    SAVE: '儲存',
    CANCEL: '取消',
    DELETE: '刪除',
    EDIT: '編輯',
    CONFIRM_DELETE_TITLE: '確認刪除',
    CONFIRM_DELETE_MESSAGE: '此操作無法復原。',
    COLUMN_SETTINGS: '欄位設定',
    ADD_NEW: '新增',
    IMPORT: '匯入',
    EXPORT: '匯出',
    RETRY: '重試',
    LOADING: '載入中...',
    OPERATIONS: '操作',
    STATUS: '狀態',
    TYPE: '類型',
    NAME: '名稱',
    DESCRIPTION: '描述',
    OWNER: '擁有者',
    CREATOR: '創建者',
    CREATED_AT: '創建時間',
    UPDATED_AT: '最後更新',
    ENABLED: '啟用',
    DISABLED: '停用',
    ALL: '全部',
    CLOSE: '關閉',
    PREVIOUS_STEP: '上一步',
    NEXT_STEP: '下一步',
    FINISH: '完成',
    ACTIONS: '操作',
    NO_DATA_TO_EXPORT: '沒有可匯出的資料。',
    LOADING_OPTIONS: '載入中...',
    SELECT_OPTION: '請選擇...',
    ALL_CATEGORIES: '所有分類',
    ALL_STATUSES: '所有狀態',
    NO_RESULTS: '找不到結果',
    SUCCESS: '成功',
    FAILED: '失敗',
    PENDING: '處理中',
    RUNNING: '執行中',
    YES: '是',
    NO: '否',
    NA: 'N/A',
  },

  MODAL: {
    DEFAULT_WIDTH: 'w-1/2',
    BASE_CLASSES: 'glass-card rounded-xl border border-slate-700/50 shadow-2xl flex flex-col max-w-4xl max-h-[80vh] animate-fade-in-down',
  },

  // Layouts & Shared Components
  APP_LAYOUT: {
    SIDEBAR_TITLE: 'SRE Platform',
    SEARCH_PLACEHOLDER: 'Search... (Ctrl+K)',
    PROFILE_MENU: {
      SETTINGS: '個人設定',
      HELP_CENTER: '幫助中心',
      LOGOUT: '登出',
    },
    HOME_BREADCRUMB: 'Home',
    TOAST: {
      LOAD_SETTINGS_ERROR: '無法載入平台設定。',
      LOGOUT_SUCCESS: '您已成功登出。',
      HELP_CENTER_NOT_CONFIGURED: '幫助中心 URL 尚未設定。',
    }
  },
  PAGE_WITH_TABS: {
    REFRESH: '刷新',
  },
  DASHBOARD_VIEWER: {
    THEME: '主題',
    THEME_DARK: '深色',
    THEME_LIGHT: '淺色',
    TV_MODE: 'TV 模式',
    TV_MODE_OFF: 'Off',
    TV_MODE_ON: 'TV',
    REFRESH: '刷新',
    REFRESH_OFF: 'Off',
    TIME: '時間',
    ZOOM_IN: 'Zoom In',
    SHARE_DASHBOARD: 'Share Dashboard',
    GRAFANA_URL_NOT_CONFIGURED: 'Grafana URL not configured.',
  },
  PLACEHOLDER_MODAL: {
    TITLE: '功能開發中',
    OK_BUTTON: '了解',
    MESSAGE: (featureName: string) => `「${featureName}」功能目前正在開發中，敬請期待！`,
  },
  UNIFIED_SEARCH: {
    TITLE: '進階搜索與篩選',
    CLEAR_FILTERS: '清除所有篩選',
    SEARCH: '搜尋',
    KEYWORD_SEARCH: '關鍵字搜尋',
    KEYWORD_PLACEHOLDER: '依關鍵字搜尋...',
    ALL_STATUSES: '所有狀態',
    ALL_SEVERITIES: '所有嚴重性',
    ALL_TYPES: '所有類型',
    ALL_PROVIDERS: '所有提供商',
    ALL_REGIONS: '所有區域',
    INCIDENTS: {
      STATUS: '狀態',
      SEVERITY: '嚴重性',
      ASSIGNEE: '處理人',
      TRIGGER_TIME_RANGE: '觸發時間範圍',
    },
    ALERT_RULES: {
      SEVERITY: '嚴重性',
    },
    RESOURCES: {
      PROVIDER: '提供商',
      REGION: '區域',
    },
  },
  ROLE_EDIT_MODAL: {
    ADD_TITLE: '新增角色',
    EDIT_TITLE: '編輯角色',
    ROLE_NAME: '角色名稱',
    PERMISSION_SETTINGS: '權限設定',
    SELECT_ALL: '全選',
  },
  EXECUTION_LOG_DETAIL: {
      STATUS: '狀態',
      SCRIPT_NAME: '腳本名稱',
      TRIGGER_SOURCE: '觸發來源',
      DURATION: '耗時',
      PARAMETERS: '執行參數',
      STDOUT: 'Standard Output (stdout)',
      STDERR: 'Standard Error (stderr)',
      TRIGGER_BY: (source: string, by: string) => `${source} by ${by}`,
      NO_STDOUT: 'No standard output.',
  },
  IMPORT_MODAL: {
    TITLE: (itemName: string) => `從 CSV 匯入${itemName}`,
    INSTRUCTIONS_TITLE: '操作說明',
    INSTRUCTIONS_STEPS: [
      '下載 CSV 範本檔案',
      '根據範本格式填寫您的資料。',
      '將填寫好的 CSV 檔案拖曳至下方區域或點擊上傳。',
    ],
    DOWNLOAD_LINK: '下載 CSV 範本檔案',
    DRAG_TEXT: '拖曳 CSV 檔案至此',
    OR: '或',
    CLICK_TO_UPLOAD: '點擊此處上傳',
    INVALID_FILE_ERROR: '請上傳有效的 CSV 檔案。',
    IMPORT_SUCCESS: (itemName: string) => `${itemName} 已成功匯入。`,
    IMPORT_ERROR: (itemName: string) => `無法匯入 ${itemName}。請檢查檔案格式並再試一次。`,
    START_IMPORT: '開始匯入',
    IMPORTING: '匯入中...',
  },

  // Pages & Modals
  SRE_WAR_ROOM: {
    PAGE_KPI_NAME: "SREWarRoom",
    AI_BRIEFING_TITLE: 'AI 每日簡報',
    STABILITY_SUMMARY: '穩定性摘要',
    KEY_ANOMALY: '關鍵異常',
    RECOMMENDED_ACTION: '建議操作',
    SERVICE_HEALTH_TITLE: '服務健康度總覽',
    RESOURCE_GROUP_STATUS_TITLE: '資源群組狀態',
    GENERATE_BRIEFING_ERROR: '無法生成 AI 簡報。請檢查 API 金鑰或稍後再試。',
  },
  INFRA_INSIGHTS: {
    TITLE: '基礎設施洞察',
    TIME_RANGE: '時間範圍',
    REFRESH: '刷新',
    EXPORT: '匯出',
    AI_RISK_PREDICTION_TITLE: 'AI 風險預測',
    RISK_DISTRIBUTION_TITLE: '風險等級分佈',
    KEY_RISK_RESOURCES_TITLE: '重點風險資源',
    RISK_LEVELS: {
      HIGH: '高風險',
      MEDIUM: '中風險',
      LOW: '低風險',
    },
    RISK_PREDICTION_ERROR: '無法生成 AI 風險預測。API 連線可能發生問題。',
    LOADING_TOPOLOGY: '載入拓撲資料中...',
  },
  CAPACITY_PLANNING: {
    TIME_RANGE_LABEL: '時間範圍',
    TRIGGER_AI_ANALYSIS: '觸發 AI 分析',
    TRENDS_CHART_TITLE: '資源使用趨勢 (含預測)',
    FORECAST_CHART_TITLE: 'CPU 容量預測模型',
    AI_SUGGESTIONS_TITLE: 'AI 優化建議',
    DETAILED_ANALYSIS_TITLE: '詳細分析',
    TABLE_HEADERS: {
      RESOURCE_NAME: '資源名稱',
      CURRENT_USAGE: '目前用量',
      FORECAST_30D: '30 天預測',
      RECOMMENDATION: '建議',
      COST_ESTIMATE: '成本估算',
    },
    IMPACT: '影響',
    EFFORT: '投入',
    FETCH_ERROR: '無法獲取容量規劃資料。',
  },
  DASHBOARD_LIST: {
    SEARCH_PLACEHOLDER: '搜尋儀表板...',
    ADD_DASHBOARD: '新增儀表板',
    DELETE_MODAL_TITLE: '確認刪除',
    DELETE_MODAL_MESSAGE: (name: string) => `您確定要刪除儀表板 ${name} 嗎？`,
    TABLE_HEADERS: {
      NAME: '名稱',
      TYPE: '類型',
      CATEGORY: '類別',
      OWNER: '擁有者',
      UPDATED_AT: '最後更新',
    },
    ACTIONS: {
      SET_AS_HOME: '設為首頁',
      SETTINGS: '設定',
    },
    HOME_BADGE: '首頁',
    BUILT_IN_TOOLTIP: '內建儀表板',
    GRAFANA_TOOLTIP: 'Grafana 儀表板',
    ALL_CATEGORIES: '全部',
    FETCH_ERROR: '無法獲取儀表板列表。',
    SAVE_ERROR: 'Failed to save dashboard.',
    DELETE_ERROR: 'Failed to delete dashboard.',
    UPDATE_ERROR: 'Failed to update dashboard.',
    BATCH_DELETE_ERROR: 'Failed to delete selected dashboards.',
  },
  ADD_DASHBOARD_MODAL: {
    STEP1_TITLE: '選擇儀表板類型',
    STEP2_TITLE: '連結 Grafana 儀表板',
    BUILT_IN_TITLE: '建立內建儀表板',
    BUILT_IN_DESC: '使用平台提供的小工具，拖拽組合出新的儀表板。',
    GRAFANA_TITLE: '連結外部 Grafana 儀表板',
    GRAFANA_DESC: '貼上 Grafana URL 或 UID，統一在平台內管理。',
    SELECT_GRAFANA_DASHBOARD: '從 Grafana 選擇儀表板 *',
    DASHBOARD_NAME: '儀表板名稱 *',
    BACK: '返回',
    SAVE_DASHBOARD: '儲存',
    PLACEHOLDER_NAME: 'e.g., Production API Metrics',
    SELECT_PLACEHOLDER: '請選擇一個儀表板...',
  },
  DASHBOARD_EDITOR: {
    EDIT_TITLE: '編輯儀表板:',
    CREATE_TITLE: '建立儀表板:',
    DEFAULT_NAME: '未命名儀表板',
    DEFAULT_DESCRIPTION: '使用者建立的內建儀表板。',
    ADD_WIDGET: '新增小工具',
    SAVE_DASHBOARD: '儲存儀表板',
    EMPTY_STATE_TITLE: '空儀表板',
    EMPTY_STATE_MESSAGE: '點擊「新增小工具」開始建立您的儀表板。',
    ADD_WIDGET_MODAL_TITLE: '新增小工具至儀表板',
    ADD_WIDGET_TITLE: '新增',
    REMOVE_WIDGET_TITLE: '移除小工具',
    NAME_REQUIRED_ERROR: '儀表板名稱為必填。',
    SAVE_SUCCESS: (name: string) => `儀表板 "${name}" 已成功儲存。`,
    UPDATE_SUCCESS: (name: string) => `儀表板 "${name}" 已成功更新。`,
    SAVE_ERROR: '儲存儀表板失敗。',
    UPDATE_ERROR: '更新儀表板失敗。',
    LOAD_ERROR: '無法載入儀表板資料。',
    EDITOR_LOAD_ERROR: '無法載入編輯器所需資料。',
    CANCEL_BUTTON: '取消',
  },
  DASHBOARD_TEMPLATES: {
    USE_TEMPLATE: '使用此範本',
  },
  INCIDENT_LIST: {
    SEARCH_PLACEHOLDER: '搜索和篩選',
    AI_ANALYSIS: 'AI 分析',
    ACKNOWLEDGE: '認領',
    RESOLVE: '解決',
    SILENCE: '靜音',
    TABLE_HEADERS: {
        SUMMARY: '摘要',
        STATUS: '狀態',
        SEVERITY: '嚴重程度',
        PRIORITY: '優先級',
        SERVICE_IMPACT: '服務影響',
        RESOURCE: '資源',
        ASSIGNEE: '處理人',
        TRIGGERED_AT: '觸發時間',
    },
    FETCH_ERROR: '無法獲取事故列表。',
    NO_EXPORT_DATA: '沒有可匯出的資料。',
    ACKNOWLEDGE_ACTION: '認領',
    COLUMN_CONFIG_SAVE_SUCCESS: '欄位設定已儲存。',
    COLUMN_CONFIG_SAVE_ERROR: '無法儲存欄位設定。',
    COLUMN_CONFIG_MISSING_ERROR: '無法儲存欄位設定：頁面設定遺失。',
    SILENCE_RULE_CREATE_ERROR: 'Failed to create silence rule.',
  },
  INCIDENT_DETAIL: {
    TITLE: (id: string) => `事故詳情: ${id}`,
    LOAD_ERROR_TITLE: '事故載入失敗',
    LOAD_ERROR_MESSAGE: (id: string) => `找不到 ID 為 "${id}" 的事故。`,
    DETAILS_TITLE: '詳細資訊',
    AI_ANALYSIS_TITLE: 'AI 自動分析',
    TIMELINE_TITLE: '時間軸',
    NO_AI_ANALYSIS: '此事故尚無 AI 分析報告。',
    NO_AI_ANALYSIS_HINT: '您可以在頂部操作列點擊「AI 分析」來產生報告。',
    STATUS: '狀態',
    SEVERITY: '嚴重性',
    PRIORITY: '優先級',
    ASSIGNEE: '指派給',
    RESOURCE: '資源',
    SERVICE_IMPACT: '服務影響',
    RULE: '規則',
    TRIGGER_TIME: '觸發時間',
  },
  ALERT_RULE_LIST: {
    ADD_RULE: '新增規則',
    TABLE_HEADERS: {
        ENABLED: '',
        NAME: '規則名稱',
        TARGET: '監控對象',
        CONDITIONS: '觸發條件',
        SEVERITY: '嚴重程度',
        AUTOMATION: '自動化',
        CREATOR: '創建者',
        UPDATED_AT: '最後更新',
    },
    ACTIONS: {
        EDIT: '編輯',
        TEST: '測試',
        COPY: '複製',
        DELETE: '刪除',
    },
    DELETE_MODAL_MESSAGE: (name: string) => `您確定要刪除告警規則 ${name} 嗎？`,
    FETCH_ERROR: '無法獲取告警規則。',
    SAVE_ERROR: 'Failed to save rule.',
    DELETE_ERROR: 'Failed to delete rule.',
    TOGGLE_ERROR: 'Failed to toggle rule status.',
    BATCH_ACTION_ERROR: (action: string) => `Failed to ${action} selected rules.`,
  },
  ALERT_RULE_EDIT_MODAL: {
    ADD_TITLE: '新增告警規則',
    EDIT_TITLE: '編輯告警規則',
    APPLY_TEMPLATE: '快速套用範本',
    STEP_TITLES: ["基本資訊", "觸發條件", "事件內容", "自動化"],
    BASIC_INFO: {
      NAME: '規則名稱 *',
      DESCRIPTION: '描述',
    },
    CONDITIONS: {
      GROUP_TITLE: (index: number) => `條件群組 #${index + 1} (OR)`,
      EVENT_SEVERITY: '事件等級:',
      ADD_AND: '新增 AND 條件',
      ADD_OR: '新增 OR 條件群組',
      METRIC_PLACEHOLDER: 'Metric (e.g., cpu.usage)',
      THRESHOLD_PLACEHOLDER: 'Threshold',
      DURATION_PLACEHOLDER: 'Duration',
    },
    CONTENT: {
      TITLE: '事件標題 *',
      CONTENT: '事件內容 *',
      VARIABLES: '可用的變數',
    },
    AUTOMATION: {
      ENABLE: '啟用自動化響應',
      SELECT_SCRIPT: '選擇腳本',
      SELECT_SCRIPT_PLACEHOLDER: '選擇一個腳本...',
      SCRIPT_PARAMS: '腳本參數',
      NO_PARAMS: '此腳本無需額外參數。',
      BOOLEAN_ENABLED: 'Enabled',
      BOOLEAN_DISABLED: 'Disabled',
    },
  },
  SILENCE_RULE_LIST: {
    ADD_RULE: '新增規則',
    TABLE_HEADERS: {
      ENABLED: '',
      NAME: '規則名稱',
      TYPE: '類型',
      MATCHERS: '靜音條件',
      SCHEDULE: '排程',
      CREATOR: '創建者',
      CREATED_AT: '創建時間',
    },
    DELETE_MODAL_MESSAGE: (name: string) => `您確定要刪除靜音規則 ${name} 嗎？`,
    FETCH_ERROR: '無法獲取靜音規則。',
    SAVE_ERROR: 'Failed to save rule.',
    DELETE_ERROR: 'Failed to delete rule.',
    TOGGLE_ERROR: 'Failed to toggle rule status.',
    BATCH_ACTION_ERROR: (action: string) => `Failed to ${action} selected rules.`,
  },
  SILENCE_RULE_EDIT_MODAL: {
    ADD_TITLE: '新增靜音規則',
    EDIT_TITLE: '編輯靜音規則',
    STEP_TITLES: ["基本資訊", "設定排程", "設定範圍"],
    BASIC_INFO: {
      APPLY_TEMPLATE: '快速套用範本',
      NAME: '規則名稱 *',
      DESCRIPTION: '描述',
    },
    SCHEDULE: {
      TYPE: '排程類型',
      SINGLE: '單次靜音',
      RECURRING: '週期性靜音',
      START_TIME: '開始時間',
      END_TIME: '結束時間',
      FREQUENCY: '重複頻率',
      EXECUTION_TIME: '執行時間',
      SELECT_WEEKDAYS: '選擇星期',
      WEEKDAYS: ['日', '一', '二', '三', '四', '五', '六'],
      CRON_EXPRESSION: 'Cron 表達式',
      CRON_EXAMPLE: "範例: '0 2 * * *' 表示每天凌晨 2 點。",
      RECURRENCE_TYPES: {
          DAILY: '每日',
          WEEKLY: '每週',
          MONTHLY: '每月',
          CUSTOM: '自訂 Cron',
      },
    },
    SCOPE: {
      TITLE: '靜音條件',
      DESCRIPTION: '定義符合哪些條件的事件將會被靜音。',
      ADD_MATCHER: '新增匹配條件',
      ENABLE_RULE: '立即啟用此靜音規則',
      SELECT_KEY: '選擇標籤鍵...',
      SELECT_VALUE: '選擇值...',
      VALUE_PLACEHOLDER: '標籤值 (e.g., api-service)',
    },
  },
  RESOURCE_LIST: {
    SEARCH_PLACEHOLDER: '搜索和篩選',
    ADD_RESOURCE: '新增資源',
    TABLE_HEADERS: {
      STATUS: '狀態',
      NAME: '名稱',
      TYPE: '類型',
      PROVIDER: 'PROVIDER',
      REGION: 'REGION',
      OWNER: '擁有者',
      LAST_CHECK_IN: '最後簽入',
    },
    ACTIONS: {
      VIEW_DETAILS: '查看詳情',
    },
    DELETE_MODAL_MESSAGE: (name: string) => `您確定要刪除資源 ${name} 嗎？`,
    FETCH_ERROR: '無法獲取資源列表。',
    SAVE_ERROR: 'Failed to save resource.',
    DELETE_ERROR: 'Failed to delete resource.',
    BATCH_DELETE_ERROR: 'Failed to delete selected resources.',
  },
  RESOURCE_DETAIL: {
    LOAD_ERROR_TITLE: '資源載入失敗',
    LOAD_ERROR_MESSAGE: (id: string) => `找不到 ID 為 "${id}" 的資源。`,
    CPU_CHART_TITLE: 'CPU Usage (last 30min)',
    MEMORY_CHART_TITLE: 'Memory Usage (last 30min)',
    RELATED_INCIDENTS_TITLE: '相關事件 (最近 3 筆)',
    NO_RELATED_INCIDENTS: '沒有相關的事件。',
    STATUS: '狀態',
    TYPE: '類型',
    PROVIDER_REGION: '提供商 / 區域',
    OWNER: '擁有者',
  },
  AUTOMATION_PLAYBOOKS: {
    ADD_SCRIPT: '新增腳本',
    DELETE_MODAL_MESSAGE: (name: string) => `您確定要刪除腳本 ${name} 嗎？`,
    FETCH_ERROR: '無法獲取自動化腳本。',
    SAVE_ERROR: 'Failed to save playbook.',
    DELETE_ERROR: 'Failed to delete playbook.',
    BATCH_DELETE_ERROR: 'Failed to delete selected playbooks.',
    RUN_ERROR: 'Failed to run playbook.',
    TABLE_HEADERS: {
        NAME: '腳本名稱',
        TRIGGER: '觸發器',
        LAST_RUN_STATUS: '上次運行狀態',
        LAST_RUN_TIME: '上次運行時間',
        RUN_COUNT: '運行次數',
    },
    ACTIONS: {
        RUN: '運行',
        EDIT: '編輯',
        DELETE: '刪除',
    }
  },
  PERSONNEL_MANAGEMENT: {
      SEARCH_PLACEHOLDER: '依名稱、Email、角色搜尋...',
      INVITE: '邀請人員',
      TABLE_HEADERS: {
          NAME: '名稱',
          ROLE: '角色',
          TEAM: '團隊',
          STATUS: '狀態',
          LAST_LOGIN: '上次登入',
      },
      DELETE_MODAL_MESSAGE: (name: string) => `您確定要刪除使用者 ${name} 嗎？`,
      FETCH_ERROR: '無法獲取人員列表。',
      INVITE_ERROR: 'Failed to invite user.',
      SAVE_ERROR: 'Failed to save user.',
      DELETE_ERROR: 'Failed to delete user.',
      BATCH_ACTION_ERROR: (action: string) => `Failed to ${action} selected users.`,
  },
  LAYOUT_SETTINGS: {
      INFO_TEXT: 'Adjust the KPI cards and their order for each hub page. Changes take effect immediately after saving.',
      AVAILABLE_WIDGETS: 'Available Columns',
      DISPLAYED_WIDGETS: 'Displayed Columns',
      CURRENTLY_DISPLAYED: 'Currently Displayed Cards:',
      NO_CARDS_DISPLAYED: 'No cards are displayed on this page.',
      LAST_UPDATED: (date: string, by: string) => `Last updated: ${date} by ${by}`,
      EDIT_MODAL_TITLE: (pageName: string) => `Edit "${pageName}" KPI Cards`,
      FETCH_ERROR: '無法獲取版面配置資料。',
      SAVE_ERROR: 'Failed to save layout configuration.',
      EDIT_BUTTON: 'Edit',
  },
  // ... continue for all other components and pages
};
