openapi: 3.1.0
info:
  title: SRE 平台 API 契約
  version: 2.25.0
  description: |
    # 版本 2.25.0
    - **新增**: 在 `POST /incidents/{incident_id}/actions` 端點中增加了 `add_note` 和 `delete_note` 操作，以支援在事件時間軸上新增和刪除備註的功能。

    # 版本 2.17.0
    - **重大重構**: 為平台所有主要模組新增了 `/.../options` API 端點，將所有 UI 相關的硬編碼資料 (如篩選條件、狀態顏色、標籤等) 全部遷移至由 API 動態提供。此舉實現了前端 UI 與業務邏輯的完全解耦，大幅提升了系統的可維護性與擴展性。

    # 版本 2.7.0
    - **新增**: 建立了 GitHub Actions 工作流程，用於在每次推送到 `main` 分支時自動將專案部署到 GitHub Pages，實現 CI/CD。

    # 版本 2.6.0
    - **新增**: 為主要列表頁面 (告警規則、靜音規則、通知策略等) 增加了後端篩選與搜尋功能。
    - **新增**: 完成了告警規則測試、規則範本、通知管道測試、自動化重試等核心功能的 API 端點。
    - **新增**: 為 CSV 匯入功能增加了對應的 API 端點。

    本文件定義 SRE 平台前後端之間的資料契約，作為後端開發的唯一真實來源 (SSOT)。
servers:
  - url: http://localhost:4000/api/v1
    description: 本地 Mock 伺服器
tags:
  - name: 認證與個人設定
    description: 登入、個人資訊與偏好設定。
  - name: AI Copilot
    description: 整合平台所有 AI 驅動的功能。
  - name: 儀表板
    description: 儀表板的 CRUD 與戰情室設定。
  - name: 事故管理 (Incidents)
    description: 事故列表、詳情、狀態變更。
  - name: 告警規則 (Grafana 代理)
    description: 告警偵測規則設定 (代理 Grafana API)。
  - name: 靜音規則
    description: 平台增值的週期性事件靜音規則。
  - name: 資源管理
    description: 資源、資源群組與拓撲視圖。
  - name: 自動化
    description: 自動化腳本、觸發器與執行歷史。
  - name: 分析中心
    description: 日誌、追蹤與容量規劃。
  - name: 身份與存取 (IAM)
    description: 人員、團隊、角色與審計日誌。
  - name: 通知管理
    description: 通知策略、管道與歷史。
  - name: 平台設定
    description: 標籤、版面與系統級配置。
  - name: 全局功能
    description: 全局搜尋與系統健康檢查。
paths:
  # ===========================================================================
  # AUTH & PROFILE
  # ===========================================================================
  /me:
    get:
      tags:
        - 認證與個人設定
      summary: 取得目前登入者的個人資訊
      operationId: getCurrentUser
      responses:
        "200":
          description: 回傳使用者基本資料與角色。
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
        "401":
          $ref: "#/components/responses/Unauthorized"
  
  /me/login-history:
    get:
      tags:
        - 認證與個人設定
      summary: 取得登入歷史紀錄
      operationId: getLoginHistory
      parameters:
        - $ref: "#/components/parameters/PageParam"
        - $ref: "#/components/parameters/PageSizeParam"
      responses:
        "200":
          description: 回傳登入歷史分頁列表。
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/PaginatedResponse"
                  - type: object
                    properties:
                      items:
                        type: array
                        items:
                          $ref: "#/components/schemas/LoginHistoryRecord"
        "401":
          $ref: "#/components/responses/Unauthorized"

  /me/preferences:
    get:
      tags:
        - 認證與個人設定
      summary: 取得使用者偏好設定
      operationId: getPreferences
      responses:
        "200":
          description: 回傳偏好設定資料。
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserPreferences"
        "401":
          $ref: "#/components/responses/Unauthorized"
    put:
      tags:
        - 認證與個人設定
      summary: 更新使用者偏好設定
      operationId: updatePreferences
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserPreferences"
      responses:
        "200":
          description: 偏好設定已更新。
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserPreferences"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"

  /me/change-password:
    post:
      tags:
        - 認證與個人設定
      summary: 變更目前登入者的密碼
      operationId: changePassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [oldPassword, newPassword]
              properties:
                oldPassword:
                  type: string
                  format: password
                newPassword:
                  type: string
                  format: password
      responses:
        "204":
          description: 密碼已成功更新。
        "400":
          description: "請求無效（例如，舊密碼不正確）。"
        "401":
          $ref: "#/components/responses/Unauthorized"
  
  # ===========================================================================
  # AI COPILOT
  # ===========================================================================
  /ai/briefing:
    get:
      tags: [AI Copilot]
      summary: 取得 SRE 戰情室 AI 每日簡報
      operationId: getAIBriefing
      responses:
        "200":
          description: 回傳最新的 AI 簡報內容。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BriefingData'
  
  /ai/briefing/generate:
    post:
      tags: [AI Copilot]
      summary: 觸發生成新的 SRE 戰情室 AI 每日簡報
      operationId: generateAIBriefing
      responses:
        "200":
          description: 回傳新生成的 AI 簡報內容。
          content:
            application/json:
              schema