import { TagDefinition, TagRegistryEntry, TagScope, TagValueKind, PiiLevel } from './types';

// 預設可寫入標籤的角色清單
const DEFAULT_WRITABLE_ROLES = ['platform_admin', 'sre_lead'];
const COMPLIANCE_WRITABLE_ROLES = ['platform_admin', 'compliance_officer'];

export const TAG_SCOPE_OPTIONS: { value: TagScope; label: string; description: string }[] = [
  { value: 'resource', label: '資源 (resource)', description: '資源與基礎設施資產。' },
  { value: 'datasource', label: '資料來源 (datasource)', description: '監控資料來源與匯入介面。' },
  { value: 'discovery_job', label: '自動探勘 (discovery_job)', description: '自動發現任務與掃描作業。' },
  { value: 'exporter', label: '匯出器 (exporter)', description: '監控匯出器與代理服務。' },
  { value: 'dashboard', label: '儀表板 (dashboard)', description: '可視化儀表板與報表。' },
  { value: 'alert_rule', label: '告警規則 (alert_rule)', description: '告警規則與閾值設定。' },
  { value: 'incident', label: '事件 (incident)', description: '事件紀錄與處理流程。' },
  { value: 'notification_policy', label: '通知策略 (notification_policy)', description: '通知路由與告警升級策略。' },
  { value: 'automation', label: '自動化 (automation)', description: '自動化腳本、排程與執行歷史。' },
  { value: 'analysis', label: '分析 (analysis)', description: '日誌、追蹤與洞察分析。' },
  { value: 'tenant', label: '租戶 (tenant)', description: '多租戶與隔離相關設定。' },
  { value: 'team', label: '團隊 (team)', description: '組織與團隊管理。' },
  { value: 'user', label: '使用者 (user)', description: '使用者與權限管理。' },
];

export const TAG_KIND_OPTIONS: { value: TagValueKind; label: string; description: string }[] = [
  { value: 'enum', label: '枚舉 (enum)', description: '僅允許從預先定義的值域中選擇。' },
  { value: 'string', label: '字串 (string)', description: '允許輸入長度不超過 128 字元的字串。' },
  { value: 'number', label: '數值 (number)', description: '允許輸入具意義的數值，需統一單位。' },
  { value: 'boolean', label: '布林 (boolean)', description: '允許 true / false 兩種值。' },
];

export const TAG_PII_LEVELS: { value: PiiLevel; label: string; description: string }[] = [
  { value: 'none', label: '無 (none)', description: '不含個資或敏感資訊。' },
  { value: 'low', label: '低 (low)', description: '含有限度的個資，需要記錄存取。' },
  { value: 'high', label: '高 (high)', description: '高度敏感資訊，需加強控管與審計。' },
];

const ALL_SCOPES = TAG_SCOPE_OPTIONS.map(option => option.value);

const registry: TagRegistryEntry[] = [
  {
    key: 'env',
    description: '部署環境 (production、staging、dev 等)。',
    scopes: ALL_SCOPES,
    kind: 'string',
    required: true,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'region',
    description: '實體或雲端機房所在區域 (例如 ap-northeast-1)。',
    scopes: ALL_SCOPES,
    kind: 'string',
    required: true,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'zone',
    description: '區域內的可用區或資料中心分區。',
    scopes: ALL_SCOPES,
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'site',
    description: '本地機房或據點代碼。',
    scopes: ALL_SCOPES,
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'rack',
    description: '機櫃編號或實體位置。',
    scopes: ['resource', 'datasource', 'discovery_job', 'analysis'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'team',
    description: '負責維運的團隊。',
    scopes: ALL_SCOPES,
    kind: 'string',
    required: true,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'owner',
    description: '業務或技術負責人。',
    scopes: ALL_SCOPES,
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'service',
    description: '所屬服務或業務域名稱。',
    scopes: ALL_SCOPES,
    kind: 'string',
    required: true,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'component',
    description: '服務內的元件或模組名稱。',
    scopes: ['resource', 'alert_rule', 'incident', 'analysis', 'automation', 'notification_policy'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'role',
    description: '資源或使用者角色 (例：database、frontend)。',
    scopes: ['resource', 'automation', 'team', 'user', 'tenant'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'business_unit',
    description: '對應的事業單位或部門。',
    scopes: ['resource', 'dashboard', 'analysis', 'notification_policy', 'tenant', 'team'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'low',
    system: true,
  },
  {
    key: 'cost_center',
    description: '財務成本中心編號。',
    scopes: ['resource', 'dashboard', 'analysis', 'tenant'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'low',
    system: true,
  },
  {
    key: 'version',
    description: '部署版本或應用程式版本號。',
    scopes: ['resource', 'service', 'automation', 'analysis', 'incident', 'notification_policy'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'commit',
    description: '對應的程式碼提交版本 (Git commit)。',
    scopes: ['resource', 'incident', 'analysis', 'automation'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'build',
    description: '建置編號或流水線代碼。',
    scopes: ['resource', 'analysis', 'automation'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'tags.schema_version',
    description: '標籤綱要的版本，用於治理與稽核。',
    scopes: ALL_SCOPES,
    kind: 'string',
    required: true,
    uniqueWithinScope: true,
    writableRoles: ['platform_admin'],
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'resource_type',
    description: '資源種類 (VM、服務、設備等)。',
    scopes: ['resource', 'alert_rule', 'incident', 'analysis', 'automation'],
    kind: 'enum',
    enumValues: ['vm', 'pod', 'service', 'device', 'plc', 'bmc', 'switch'],
    required: true,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'os',
    description: '作業系統名稱。',
    scopes: ['resource', 'analysis'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'distro',
    description: '作業系統發行版 (例如 ubuntu、alpine)。',
    scopes: ['resource', 'analysis'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'kernel',
    description: '核心版本。',
    scopes: ['resource', 'analysis'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'ip',
    description: 'IPv4/IPv6 位址。',
    scopes: ['resource', 'datasource', 'discovery_job', 'exporter'],
    kind: 'string',
    required: false,
    uniqueWithinScope: true,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'low',
    system: true,
  },
  {
    key: 'hostname',
    description: '主機名稱。',
    scopes: ['resource', 'datasource', 'exporter'],
    kind: 'string',
    required: false,
    uniqueWithinScope: true,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'low',
    system: true,
  },
  {
    key: 'vendor',
    description: '設備或服務供應商。',
    scopes: ['resource', 'datasource', 'exporter'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'model',
    description: '硬體或設備型號。',
    scopes: ['resource', 'exporter'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'cluster',
    description: '所屬叢集名稱。',
    scopes: ['resource', 'datasource', 'discovery_job', 'alert_rule', 'incident', 'analysis'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'namespace',
    description: 'Kubernetes Namespace 或邏輯分區。',
    scopes: ['resource', 'alert_rule', 'incident', 'analysis'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'workload',
    description: '應用工作負載名稱 (Deployment、Job 等)。',
    scopes: ['resource', 'alert_rule', 'incident'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'datasource_type',
    description: '資料來源類型。',
    scopes: ['datasource', 'alert_rule', 'incident', 'analysis'],
    kind: 'enum',
    enumValues: ['prometheus', 'victoriametrics', 'loki', 'tempo', 'grafana'],
    required: true,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'datasource_id',
    description: '資料來源唯一識別碼。',
    scopes: ['datasource', 'alert_rule', 'incident', 'analysis'],
    kind: 'string',
    required: true,
    uniqueWithinScope: true,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'low',
    system: true,
  },
  {
    key: 'exporter_type',
    description: '匯出器類型。',
    scopes: ['exporter', 'resource', 'alert_rule', 'incident'],
    kind: 'enum',
    enumValues: ['node', 'snmp', 'modbus', 'ipmi', 'cadvisor', 'kube_state'],
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'protocol',
    description: '通訊協定 (SNMP、MODBUS 等)。',
    scopes: ['datasource', 'discovery_job', 'exporter'],
    kind: 'enum',
    enumValues: ['snmp', 'modbus', 'opcua', 'ipmi', 'mqtt'],
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'discovery_job_id',
    description: '自動探勘任務 ID。',
    scopes: ['discovery_job', 'resource'],
    kind: 'string',
    required: false,
    uniqueWithinScope: true,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'edge_gateway',
    description: '是否為邊緣匯流排節點。',
    scopes: ['datasource', 'discovery_job', 'resource'],
    kind: 'boolean',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'gateway_id',
    description: '邊緣匯流排識別碼。',
    scopes: ['datasource', 'discovery_job'],
    kind: 'string',
    required: false,
    uniqueWithinScope: true,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'rule_id',
    description: '告警規則 ID。',
    scopes: ['alert_rule', 'incident', 'notification_policy', 'automation'],
    kind: 'string',
    required: true,
    uniqueWithinScope: true,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'rule_template',
    description: '告警規則模板或範本。',
    scopes: ['alert_rule'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'metric',
    description: '監控指標名稱。',
    scopes: ['alert_rule', 'analysis'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'metric_family',
    description: '指標族群或類別。',
    scopes: ['alert_rule', 'analysis'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'threshold_profile',
    description: '閾值設定模板名稱。',
    scopes: ['alert_rule'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'window',
    description: '評估時間窗 (ISO8601 duration)。',
    scopes: ['alert_rule'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'operator',
    description: '閾值比較運算子。',
    scopes: ['alert_rule'],
    kind: 'enum',
    enumValues: ['>', '>=', '<', '<='],
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'slo',
    description: '服務等級目標識別碼。',
    scopes: ['alert_rule', 'incident', 'analysis'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'sla',
    description: '服務等級協議識別碼。',
    scopes: ['notification_policy', 'incident'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'status',
    description: '事件狀態。',
    scopes: ['incident', 'notification_policy', 'automation'],
    kind: 'enum',
    enumValues: ['New', 'Acknowledged', 'Resolved', 'Silenced'],
    required: true,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'severity',
    description: '事件嚴重度。',
    scopes: ['incident', 'notification_policy', 'automation', 'analysis'],
    kind: 'enum',
    enumValues: ['Info', 'Warning', 'Critical'],
    required: true,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'impact',
    description: '事件影響層級 (取代 priority / service_impact)。',
    scopes: ['incident', 'notification_policy', 'automation'],
    kind: 'enum',
    enumValues: ['High', 'Medium', 'Low'],
    required: true,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'resource_id',
    description: '受影響的資源 ID。',
    scopes: ['incident', 'automation', 'analysis'],
    kind: 'string',
    required: true,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'affected_service',
    description: '受影響的服務名稱。',
    scopes: ['incident', 'notification_policy', 'analysis'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'silenced',
    description: '事件是否被靜音。',
    scopes: ['incident', 'notification_policy'],
    kind: 'boolean',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'maintenance_window',
    description: '對應的維護視窗識別碼。',
    scopes: ['incident', 'notification_policy'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'channel',
    description: '通知路由使用的管道。',
    scopes: ['notification_policy'],
    kind: 'enum',
    enumValues: ['email', 'slack', 'pagerduty', 'webhook'],
    required: true,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'routing_key',
    description: '通知系統使用的路由鍵。',
    scopes: ['notification_policy'],
    kind: 'string',
    required: false,
    uniqueWithinScope: true,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'low',
    system: true,
  },
  {
    key: 'oncall_team',
    description: '值班團隊名稱。',
    scopes: ['notification_policy', 'incident'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'playbook_id',
    description: '對應的自動化腳本 ID。',
    scopes: ['automation', 'incident'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'playbook_type',
    description: '自動化腳本類型。',
    scopes: ['automation'],
    kind: 'enum',
    enumValues: ['shell', 'python', 'ansible', 'n8n'],
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'safe_mode',
    description: '自動化腳本是否啟用安全模式。',
    scopes: ['automation'],
    kind: 'boolean',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'none',
    system: true,
  },
  {
    key: 'lineage_id',
    description: '資料血緣識別碼。',
    scopes: ['analysis', 'incident'],
    kind: 'string',
    required: false,
    uniqueWithinScope: true,
    writableRoles: COMPLIANCE_WRITABLE_ROLES,
    piiLevel: 'low',
    system: true,
  },
  {
    key: 'dataset',
    description: '資料集名稱。',
    scopes: ['analysis'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: COMPLIANCE_WRITABLE_ROLES,
    piiLevel: 'low',
    system: true,
  },
  {
    key: 'pii',
    description: '資料敏感等級。',
    scopes: ['analysis'],
    kind: 'enum',
    enumValues: ['none', 'low', 'high'],
    required: false,
    uniqueWithinScope: false,
    writableRoles: COMPLIANCE_WRITABLE_ROLES,
    piiLevel: 'high',
    system: true,
  },
  {
    key: 'retention_class',
    description: '資料保存等級。',
    scopes: ['analysis'],
    kind: 'enum',
    enumValues: ['hot', 'warm', 'cold', 'archive'],
    required: false,
    uniqueWithinScope: false,
    writableRoles: COMPLIANCE_WRITABLE_ROLES,
    piiLevel: 'low',
    system: true,
  },
  {
    key: 'compliance',
    description: '遵循的法規或標準。',
    scopes: ['analysis', 'tenant'],
    kind: 'enum',
    enumValues: ['iso27001', 'soc2', 'pci'],
    required: false,
    uniqueWithinScope: false,
    writableRoles: COMPLIANCE_WRITABLE_ROLES,
    piiLevel: 'low',
    system: true,
  },
  {
    key: 'tenant',
    description: '租戶或客戶識別碼。',
    scopes: ['tenant', 'team', 'user', 'resource', 'incident', 'analysis'],
    kind: 'string',
    required: true,
    uniqueWithinScope: false,
    writableRoles: ['platform_admin'],
    piiLevel: 'low',
    system: true,
  },
  {
    key: 'realm',
    description: '身份驗證領域或網域。',
    scopes: ['tenant', 'user'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: ['platform_admin'],
    piiLevel: 'low',
    system: true,
  },
  {
    key: 'user',
    description: '使用者識別碼或帳號。',
    scopes: ['team', 'user', 'incident', 'automation'],
    kind: 'string',
    required: false,
    uniqueWithinScope: false,
    writableRoles: DEFAULT_WRITABLE_ROLES,
    piiLevel: 'high',
    system: true,
  },
];

const createTagDefinition = (entry: TagRegistryEntry): TagDefinition => ({
  id: `tag-${entry.key}`,
  ...entry,
  allowedValues:
    entry.kind === 'enum'
      ? (entry.enumValues ?? []).map((value, index) => ({
          id: `${entry.key}:${value}:${index}`,
          value,
          usageCount: 0,
        }))
      : [],
  usageCount: 0,
});

export const TAG_REGISTRY = registry;

export const createTagDefinitions = (): TagDefinition[] => registry.map(entry => createTagDefinition(entry));

export const getTagRegistryEntry = (key: string): TagRegistryEntry | undefined => registry.find(entry => entry.key === key);

export const getEnumValuesForTag = (key: string): string[] => getTagRegistryEntry(key)?.enumValues ?? [];

